### ISSUE TITLE
Ошибка в методе НайтиСовпадения

### ISSUE THREAD

**Issue by sorxros** [alexkmbk/RegEx1CAddin#1]
При передаче в метод длинного текста (пробовал на 500 символах) клиент падает!
Очень прошу пофиксить! Разработка очень нужна в жизни!%)

**Comment by alexkmbk** [comment]
А не могли бы прикрепить текст и выражение на котором падает?

**Comment by alexkmbk** [comment]
@sorxros  Большое спасибо!

**Comment by alexkmbk** [comment]
@sorxros Сходу не воспроизвелось, проверял на 32-х битном клиенте, на windows 7. Попробуйте скачать и проверить на последней, 4-ой версии компоненты - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/4

Если ошибка остается, прошу уточнить версию и разрядность платформы и ОС.

**Comment by sorxros** [comment]
Пользуюсь 4 версией. Ошибка повторяется регулярно. У меня win 10 pro 64x. Пробую в файловой БД. Сейчас подозреваю, что проблема не в длине строки, а в переносе строки (Символы.ПС). Продолжаю  исследовать.

**Comment by sorxros** [comment]
Мой код в общем-то такой же.
Пользуюсь платформой 8.3.12.1714. Возможно это баг платформы или файловой версии платформы.

**Comment by alexkmbk** [comment]
@sorxros Воспроизвелось и у меня, это падает на 64-битном клиенте платформы. То есть проблема в 64-битной версии компоненты.

**Comment by sorxros** [comment]
Я тоже попробую разобраться. Если получится, то создам pull request.

**Comment by alexkmbk** [comment]
@sorxros в качестве обходного решения можно обрабатывать текст построчно. Пока с проблемой разобраться не удалось, думаю может быть попробовать библиотеку boost.

**Comment by alexkmbk** [comment]
@sorxros Прикладываю отдельным файлом 64-битную версию компоненты, собранную на библиотеке boost. На ней ошибки нет.

[RegExWin64.zip](https://github.com/alexkmbk/RegEx1CAddin/files/2674529/RegExWin64.zip)

**Comment by alexkmbk** [comment]
@sorxros 

Выложена новая версия компоненты под номером 5.
В ней был добавлен ряд новых возможностей и исправлена данная ошибка.
Правда на текущий момент потеряна совместимость с Windows XP.

https://github.com/alexkmbk/RegEx1CAddin/releases/tag/5

**Comment by sorxros** [comment]
Большое спасибо!
