### ISSUE TITLE
Реализовать выброс исключения с указанием описания ошибки

### ISSUE THREAD

**Issue by tormozit** [alexkmbk/RegEx1CAddin#11]
Сейчас каждый вызов метода компоненты приходится заворачивать в попытку и перевыбрасывать исключение с передачей описания ошибки их свойства ОписаниеОшибки. Это довольно неудобно. Хотелось бы выброс исключения из самой компоненты с указанием описания ошибки без необходимости перевыброса в коде 1С.

**Comment by alexkmbk** [comment]
К сожалению нет технической возможности установить текст ошибки, возвращаемый функцией ОписаниеОшибки(), поэтому и было добавлено свойство ОписаниеОшибки. 
В NAtiveAPI есть метод AddError, который казалось бы должен решать эту проблему, но по факту, с помощью  него, не устанавливается текст ошибки, возвращаемый функцией ОписаниеОшибки().
