### ISSUE TITLE
Свойство ОписаниеОшибки заполняется в какой то странной кодировке

### ISSUE THREAD

**Issue by tormozit** [alexkmbk/RegEx1CAddin#12]
Свойство ОписаниеОшибки содержит например текст
`T h e   r e g e x p   t e m p l a t e   i s   n o t   s p e c i f i e d . :   u n m a t c h e d   c l o s i n g   p a r e n t h e s i s :   :   T h e   r e g e x p   t e m p l a t e   i s   n o t   s p e c i f i e d . :   u n m a t c h e d   c l o s i n g   p a r e n t h e s i s :   :   T h e   r e g e x p   t e m p l a t e   i s   n o t   s p e c i f i e d . :   u n m a t c h e d   c l o s i n g   p a r e n t h e s i s :   :   T h e `

![изображение](https://user-images.githubusercontent.com/11896251/117533217-4f2a8600-aff4-11eb-9752-1e967a3507f1.png)
![изображение](https://user-images.githubusercontent.com/11896251/117533218-4f2a8600-aff4-11eb-8f27-9a388f243c94.png)

При выводе в окно сообщений такого текста появляется только буква "Т"

**Comment by alexkmbk** [comment]
Исправлено.
