### ISSUE TITLE
Сборка не пошла

### ISSUE THREAD

**Issue by Evgeny1103** [alexkmbk/RegEx1CAddin#17]
**В среде: Win10,  VS2022**

Сборка начата…
1>------ Сборка начата: проект: RegEx, Конфигурация: Debug x64 ------
1>cl : командная строка warning D9035: использование параметра "Gm" нежелательно, он будет удален в следующих выпусках
1>stdafx.cpp
1>cl : командная строка warning D9035: использование параметра "Gm" нежелательно, он будет удален в следующих выпусках
1>StrConv.cpp
1>json.cpp
1>AddInNative.cpp
1>C:\Users\evgen\source\repos\RegEx1CAddin-master\AddInNative.cpp(38,27): warning C4311: приведение типов: усечение указателя из "IComponentBase *" в "long"
1>C:\Users\evgen\source\repos\RegEx1CAddin-master\AddInNative.cpp(38,27): warning C4302: приведение типов: усечение из "IComponentBase *" к "long"
1>C:\Users\evgen\source\repos\RegEx1CAddin-master\AddInNative.cpp(197,5): warning C4267: аргумент: преобразование из "size_t" в "unsigned long"; возможна потеря данных
........**.. и так далее, Затем**
1>dllmain.cpp
1>   Создается библиотека C:\Users\evgen\source\repos\RegEx1CAddin-master\\bind64\RegExWin64.lib и объект C:\Users\evgen\source\repos\RegEx1CAddin-master\\bind64\RegExWin64.exp
1>AddInNative.obj : error LNK2019: ссылка на неразрешенный внешний символ pcre2_compile_16 в функции "private: struct pcre2_real_code_16 * __cdecl CAddInNative::GetPattern(struct _tVariant const *)" (?GetPattern@CAddInNative@@AEAAPEAUpcre2_real_code_16@@PEBU_tVariant@@@Z).
1>AddInNative.obj : error LNK2019: ссылка на неразрешенный внешний символ pcre2_code_free_16 в функции "public: virtual __cdecl CAddInNative::~CAddInNative(void)" (??1CAddInNative@@UEAA@XZ).

Пожалуйста,  подскажите. Опыт небольшой в проектах такого рода,  фактически проект использую для изучения темы 1С внешние компоненты и освоения VS и С++ (очень-очень  давно опыт с С был),  сам  не докопаюсь до причины, видимо.

**Comment by alexkmbk** [comment]
Проект Visual Studio не настроен на сборку отладночной 64-битной версии. Попробуйте собрать или Release или Debug но для x86.

**Comment by Evgeny1103** [comment]
В среде: Win10 х 64, VS2022  не получилось. Пришлось установить  VS 2017 c  поддержкой Windows XP для С++.  При сборке  релизов много **предупреждений** о возможной потере данных при преобразовании типов, а также  об  усечении указателя, и outputbuffer: неиспользованная локальная переменная. 
 **Ошибок** не было.  
Работа компоненты х64 проверена на  платформе 1С x64  8.3.18  на предложенном  alexmbk  Примере использования. [https://github.com/alexkmbk/RegEx1CAddin#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F]
Спасибо.

**Comment by Evgeny1103** [comment]
Благодарю, спасибо за мгновенную реакцию.
