### ISSUE TITLE
info.xml для БСП ВнешниеКомпаненты

### ISSUE THREAD

**Issue by asosnoviy** [alexkmbk/RegEx1CAddin#2]
```xml
<?xml version="1.0" encoding="utf8"?>
<info>
	<progid>RegEx</progid>
	<name>RegEx1CAddin</name>
	<version>1.10.1</version>
</info>
```

Если в zip подложить ифо, тогда при загрузке в справочник  данные подтянутся сами.

![image](https://user-images.githubusercontent.com/15638529/59917954-ff586b00-942b-11e9-8245-d373408686f3.png)

**Comment by alexkmbk** [comment]
Большое спасибо!

**Comment by alexkmbk** [comment]
@asosnoviy 
Добавил в [последней тестовой сборке ](https://github.com/alexkmbk/RegEx1CAddin/releases/tag/11)этот файл.
