### ISSUE TITLE
При многократном поиске выражения "{1}" размножается описание ошибки

### ISSUE THREAD

**Issue by tormozit** [alexkmbk/RegEx1CAddin#20]
Создал объект компоненты и много раз вызывал поиск по некорректному шаблону "{1}". Каждый раз я получал описание ошибки со все большим числом повторов текста.  Видимо где то не очищается описание ошибки при генерации исключения в компоненте.

{Обработка.ирОболочкаРегВыражение.МодульОбъекта(116)}: The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item: : : : : : The regexp template is not specified.: : quantifier does not follow a repeatable item

**Comment by alexkmbk** [comment]
В версии [14](https://github.com/alexkmbk/RegEx1CAddin/releases/tag/14.2) исправлялась похожая ошибка, может быть используется более старая версия?

**Comment by tormozit** [comment]
использую версию 13

**Comment by alexkmbk** [comment]
> использую версию 13

Тогда должно исправиться на версии 14
