### ISSUE TITLE
Ошибка при установке шаблона "\(.*?\)"

### ISSUE THREAD

**Issue by tormozit** [alexkmbk/RegEx1CAddin#24]
Присваиваю свойству Pattern значение `\(.*?\)`
В свойстве "ОписаниеОшибки" появляется
: : unrecognized character follows \: : : unrecognized character follows \: : : unrecognized character follows \: : : unrecognized character follows \

**Comment by tormozit** [comment]
По всей видимости тут множественная ошибка. Еще не очищается свойство ОписаниеОшибки и там копятся ошибка от разных ситуаций. А исходно заполнение этого свойства вызывал шаблон "\O", в котором я ошибочно поставил "\"

**Comment by alexkmbk** [comment]
> По всей видимости тут множественная ошибка. Еще не очищается свойство ОписаниеОшибки и там копятся ошибка от разных ситуаций. А исходно заполнение этого свойства вызывал шаблон "\O", в котором я ошибочно поставил ""

Попробуйте обновиться на актуальную версию https://github.com/alexkmbk/RegEx1CAddin/releases/tag/14.2, там ошибка с накоплением текстов ошибок исправлялась.

**Comment by tormozit** [comment]
Да. В актуальной версии исправлено
