### ISSUE TITLE
Планируется ли делать аналог свойства SubMatches в VBScript.RegExp в результате поиска совпадений?

### ISSUE THREAD

**Issue by LevkinSergey** [alexkmbk/RegEx1CAddin#3]

**Comment by alexkmbk** [comment]
Точно в таком виде не планируется, поскольку есть ограничение со стороны протокола NativeAPI на то, какие типы значений может возвращать внешняя компонента. Но принимаются предложения по расширению функционала для решения проблемы обхода групп результатов поиска.

Вот здесь уже поднимали вопрос по этой проблеме - http://forum.infostart.ru/forum28/topic203542/message2261568/#message2261568

**Comment by LevkinSergey** [comment]
> Но принимаются предложения по расширению функционала для решения проблемы обхода групп результатов поиска.

У меня две идеи. Вторая на мой взгляд проще в использовании.

**Первый вариант**. Реализовать метод _Выбрать()_, который будет производить выборку в  текущей группе. И обходить группу уже существующим методов следующий(). На 1С код по обходу примерно следующий будет

```
Рег.НайтиСовпадения("Hello world", "([A-Za-z]+)\s+([a-z]+)");

//Обходим MatchCollection
Пока Рег.Следующий() Цикл
ТекстMatch=Рег.ТекущееЗначение;

 //Обходим SubMatches
Рег.Выбрать();
Пока Рег.Следующий() Цикл
 ТекстSubMatch=Рег.ТекущееЗначение;
КонецЦикла;

КонецЦикла;
```

**Второй вариант**. Реализуем еще один метод *СледующийПодчиненный()*, Который будет обходить коллекцию SubMatches. Код в 1С по обходу примерно следующий

```
Рег.НайтиСовпадения("Hello world", "([A-Za-z]+)\s+([a-z]+)");

//Обходим MatchCollection
Пока Рег.Следующий() Цикл
ТекстMatch=Рег.ТекущееЗначение;

 //Обходим SubMatches
Пока Рег.СледующийПодчиненный() Цикл
 ТекстSubMatch=Рег.ТекущееЗначение;
КонецЦикла;

КонецЦикла;
```

**Comment by alexkmbk** [comment]
@LevkinSergey 
Большое спасибо за предолжения!

Мне ближе второй вариант, я бы сделал так:
1) чтобы не ломать совместимость с сущетсвующим поведением, добавить признак ИерархическийОбходРезультатов, со значением по умолчанию Ложь.

Если ИерархическийОбходРезультатов = Истина, тогда метод Следующий() будет обходить только верхний уровень, то есть целиком найденную строку, без вложенных групп.

2) добавить метод КоличествоВложенныхГрупп(), который будет возвращать количество групп в результатах запроса (количество всегда фиксировано для заданного шаблона).

3) добавить метод ПолучитьПодгруппу(ИндексГруппы), который будет возвращать значение найденной группы по индексу.

**Comment by LevkinSergey** [comment]
так даже лучше получается. 
Только один вопрос. 
После позиционирования на подгруппе методом ПолучитьПодгруппу(ИндексПодгруппы), можно ли будет обойти ее с помощью метода Следующий()?

**Comment by alexkmbk** [comment]
> 
> 
> так даже лучше получается.
> Только один вопрос.
> После позиционирования на подгруппе методом ПолучитьПодгруппу(ИндексПодгруппы), можно ли будет обойти ее вхождения с помощью метода Следующий()?

Метод ПолучитьПодгруппу будет возвращать само строковое значение найденной подгруппы. То есть это не позиционирование, а именно получение значения.

Например:

```
Рег.ИерархическийОбходРезультатов = Истина;
Рег.НайтиСовпадения("Hello world", "([A-Za-z]+)\s+([a-z]+)");

Сообщить( Рег.КоличествоВложенныхГрупп()); // 2

//Обходим MatchCollection
Пока Рег.Следующий() Цикл
ТекстMatch=Рег.ТекущееЗначение; // Hello world
Сообщить(Рег.ПолучитьПодгруппу(0)) // Hello
Сообщить(Рег.ПолучитьПодгруппу(1)) // World
КонецЦикла;
```

**Comment by LevkinSergey** [comment]
понял. То что нужно.

**Comment by alexkmbk** [comment]
@LevkinSergey 
Выложил[ тестовую сборку](https://github.com/alexkmbk/RegEx1CAddin/releases/tag/11), пока только для Windows и Linux.

Реализовал новый функционал по описанной мной ранее схеме, за исключением добавления параметра ИерархическийОбходРезультатов . Его добавлять не стал, вместо этого, добавил этот признак третьим параметром в методе НайтиСовпадения / Matches.

**Comment by LevkinSergey** [comment]
будет ли сборка для браузеров 11-й версии в ближайшее время?

**Comment by alexkmbk** [comment]
> будет ли сборка для браузеров 11-й версии в ближайшее время?

В ближайшее время собрать к сожалению нет времени.

**Comment by alexkmbk** [comment]
@LevkinSergey 
> будет ли сборка для браузеров 11-й версии в ближайшее время?

Добавлена сборка для веб браузера Google Chrome под Windows - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/11.6

**Comment by LevkinSergey** [comment]
Вроде работает. Спасибо. 

Добавил новые методы и описал наконец подсистему, основанную на вашей компоненте
https://github.com/cpr1c/RegEx1C_cfe
