### ISSUE TITLE
Не верно отрабатывает регулярка.

### ISSUE THREAD

**Issue by DitriXNew** [alexkmbk/RegEx1CAddin#4]
Есть регулярка  `\<(?!Auto)[a-zA-z]+\s?.?[0-9a-zA-Z]+\>`
Работает вот так:
![image](https://user-images.githubusercontent.com/11927866/91191661-e4c1f780-e6a9-11ea-800f-91732be7d6d7.png)
Но тут, увы, регулярка выбирает абсолютно все слова, разделяя их пробелом, причем ей все равно на теги.
Это баг, или я что то не то делаю?

**Comment by alexkmbk** [comment]
Здесь реализация на движке из библиотеки boost.regex, она может отличаться от реализации на regex101. Уже известно несколько отличий.

Надо подумать, но сходу попробовал, у меня отработало как вы ожидали если убрать из шаблона слэши \.

**Comment by alexkmbk** [comment]
Вот в такой форме регулярка тоже работает: <(?!Auto)[a-zA-z]+\s?.?[0-9a-zA-Z]+>

**Comment by alexkmbk** [comment]
@DitriXNew Опубликована тестовая версия компоненты под Windows и Linux на движке pcre2  - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/13.0

В этой версии, данная регулярка отрабатыват как ожидалось, без необходимости внесения изменений.
