### ISSUE TITLE
Доступность на ВебКлиенте

### ISSUE THREAD

**Issue by lufton** [alexkmbk/RegEx1CAddin#6]
Есть ли способ установить данную компоненту в ВебКлиенте? Получаю вот такое сообщение при вызове:
`НачатьУстановкуВнешнейКомпоненты(Новый ОписаниеОповещения("КомпонентаRegExУстановлена", НПR), "ОбщийМакет.RegEx");`
![image](https://user-images.githubusercontent.com/2139755/101290127-0f732e80-3809-11eb-8443-048df5e12a13.png)
При этом на тонком клиенте всё работает.

**Comment by alexkmbk** [comment]
@lufton Да, есть поддержка google chrome. Для 10-ой версии компоненты есть собранный архив для веб браузеров - RegEx1CAddin_Browsers_10.zip - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/10.
Для 11-ой версии архив компонент для браузеров пока не собран.

**Comment by alexkmbk** [comment]
@lufton Добавлена сборка для веб браузера Google Chrome под Windows - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/11.6

**Comment by lufton** [comment]
> @lufton Добавлена сборка 11-ой версии для веб браузера Google Chrome под Windows - https://github.com/alexkmbk/RegEx1CAddin/releases/tag/11.6

Спасибо!
